backend:
  name: git-gateway
  branch: master
media_folder: src/assets
public_folder: /assets

collections:
  - name: "homepage"
    label: "Homepage"
    folder: "content/homepage"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "home-page"}
      - {label: "Hero Title", name: "heroTitle", widget: "string"}
      - {label: "Hero Description", name: "heroDescription", widget: "text"}
      - {label: "Featured Image", name: "thumbnail", widget: "image", choose_url: true, default: "/uploads/chocolate-dogecoin.jpg", media_library: {config: multiple: true}}
  - name: "tour_dates" # New collection for tour dates
    label: "Tour Dates"
    folder: "content/tour_dates"
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Date", name: "date", widget: "date", format: "MMM Do, YYYY"}
      - {label: "Location", name: "location", widget: "string"}
  - name: "facebook_videos" # New collection for tour dates
    label: "Tour Dates"
    folder: "content/tour_dates"
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Date", name: "date", widget: "date", format: "MMM Do, YYYY"}
      - {label: "Location", name: "location", widget: "string"}

  - name: "home"
    label: "Home"
    label_singular: "Homepage" # Used in the UI, ie: "New Post"
    files:
      - file: "content/home.md"
        label: "Homepage"
        name: "homepage"
        fields:
          - { label: "Header", name: "header", widget: "string"}
          - { label: "Subtitle", name: "subtitle", widget: "string", required: false}
          - { label: "Featured Post", name: "featuredPost", widget: "relation", collection: "pages", searchFields: ["title"], displayFields: ["title"], required: false }
          - { label: "Body", name: "body", widget: "markdown"}

