backend:
  name: git-gateway
  branch: main

publish_mode: editorial_workflow

media_folder: "static/images"
public_folder: "/images"

collections:
  - name: "homepage"
    label: "Homepage"
    folder: "content/homepage"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "home-page"}
      - {label: "Hero Title", name: "heroTitle", widget: "string"}
      - {label: "Hero Description", name: "heroDescription", widget: "text"}
